pipeline {
  agent {
      node {
          label 'jenkins-agent-python'
      }
  }
  triggers {
    pollSCM 'H/5 * * * *'
  }
    stages {
        stage("build") {
          steps{
            echo 'building the application'
            echo ${path}
            sh '''
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install selenium==4.9.1
            pip install webdriver-manager
            pip install webdrivermanager
            '''
            }
        }
       stage("test") {
          steps{
            echo 'testing the application'
            sh '''
            cd pythonProject/Integration-folder-01
            python3 Test-001.py
            '''
            sh '''
            cd pythonProject/Integration-folder-01
            python -m robot Test-002.robot 
            '''
          }
        }
       stage("deploy") {
          steps{
            echo 'deploying the application'
          }
        }
    }
}
