pipeline {
  agent {
      node {
          label 'jenkins-agent-python'
      }
  }
  triggers {
    pollSCM 'H/5 * * * *'
  }
    stages {
        stage("build") {
          steps{
            echo 'building the application'
            }
        }
       stage("test") {
          steps{
            echo 'testing the application'
            
          }
        }
       stage("deploy") {
          steps{
            echo 'deploying the application'
          }
        }
    }
}
